[package]
name = "linux_rgb_daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systemstat = "0.1.10"
serial = "0.4.0"
chrono = "0.4"
